# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jamie Burleigh
description: > # this means to ignore newlines until "baseurl:"
  A portfolio site built with Jekyll, based on hack.css
repository: jburleigh1.github.io
baseurl: ""  # the subpath of your site, e.g. /blog
url: http://jburleigh1.github.io  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: standard  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Jamie Burleigh
email: j.burleigh1@gmail.com

navigation:
  - text: Home
    url: /

projects:
  - name: git-secret
    description: A bash-tool to store your private data inside a git repository.
    link: https://sobolevn.github.io/git-secret
    image: https://github.com/sobolevn/git-secret/blob/7c9ae0b1853d4c15549027524121b9e40219fe47/images/git-secret-sm.png?raw=true 

social:
  - service: github
    username: jburleigh1
    link: https://github.com/jburleigh1
  - service: twitter
    username: jburleigh1
    link: https://twitter.com/jburleigh1
